FROM node:22-alpine
RUN apk add --no-cache libc6-compat ffmpeg
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npx prisma generate

CMD ["npx", "tsx", "src/workers/index.ts"]
